export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/categories/pizza.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/categories/burger.png"),
  },
  {
    id: 3,
    name: "Rolls",
    image: require("../assets/images/categories/rolls.png"),
  },
  {
    id: 4,
    name: "Biryani",
    image: require("../assets/images/categories/biryani.png"),
  },
  {
    id: 5,
    name: "Chicken",
    image: require("../assets/images/categories/chicken.png"),
  },
  {
    id: 6,
    name: "Ice Cream",
    image: require("../assets/images/categories/icecream.png"),
  },
  {
    id: 7,
    name: "Thali",
    image: require("../assets/images/categories/thali.png"),
  },
  {
    id: 8,
    name: "Idli",
    image: require("../assets/images/categories/idli.png"),
  },
  {
    id: 9,
    name: "Cake",
    image: require("../assets/images/categories/cake.png"),
  },
  {
    id: 10,
    name: "Noodles",
    image: require("../assets/images/categories/noodles.png"),
  },
  {
    id: 11,
    name: "Momos",
    image: require("../assets/images/categories/momos.png"),
  },
  {
    id: 12,
    name: "Paneer",
    image: require("../assets/images/categories/paneer.png"),
  },
];

export const featured = [
  {
    id: 1,
    title: "Pizza Hut",
    description: "50% OFF Upto ₹100",
    restaurants: [
      {
        id: 1,
        title: "Pizza Hut",
        name: "Classic Sweet Corn Pizza",
        image: require("../assets/images/dishes/pizza-1.jpg"),
        description:
          "Explore curated lists of top restaurants, cafes, pubs, and bars in Delhi NCR, based on trends",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 5,
        reviews: "4.4k",
        category: "₹250 For One",
        dishes: [
          {
            id: 1,
            name: "Classic Sweet Corn Pizza",
            description: "Pizza Hut",
            price: 250,
            image: require("../assets/images/dishes/pizza-1.jpg"),
          },
          {
            id: 2,
            name: "Tandoor Panner Pizza",
            description: "Pizza Hut",
            price: 450,
            image: require("../assets/images/dishes/pizza-2.jpg"),
          },
          {
            id: 3,
            name: "Cheese Supreme Pizza",
            description: "Pizza Hut",
            price: 350,
            image: require("../assets/images/dishes/pizza-3.jpg"),
          },
        ],
      },
      {
        id: 2,
        title: "Pizza Hut",
        name: "Tandoor Paneer Pizza",
        image: require("../assets/images/dishes/pizza-2.jpg"),
        description:
          "Explore curated lists of top restaurants, cafes, pubs, and bars in Delhi NCR, based on trends",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4.5,
        reviews: "4.4k",
        category: "₹450 For One",
        dishes: [
          {
            id: 1,
            name: "Tandoor Panner Pizza",
            description: "Pizza Hut",
            price: 450,
            image: require("../assets/images/dishes/pizza-2.jpg"),
          },
          {
            id: 2,
            name: "Classic Sweet Corn Pizza",
            description: "Pizza Hut",
            price: 250,
            image: require("../assets/images/dishes/pizza-1.jpg"),
          },
          {
            id: 3,
            name: "Cheese Supreme Pizza",
            description: "Pizza Hut",
            price: 350,
            image: require("../assets/images/dishes/pizza-3.jpg"),
          },
        ],
      },
      {
        id: 3,
        title: "Pizza Hut",
        name: "Cheese Supreme Pizza",
        image: require("../assets/images/dishes/pizza-3.jpg"),
        description:
          "Explore curated lists of top restaurants, cafes, pubs, and bars in Delhi NCR, based on trends",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 5,
        reviews: "5.4k",
        category: "₹350 For One",
        dishes: [
          {
            id: 1,
            name: "Cheese Supreme Pizza",
            description: "Pizza Hut",
            price: 350,
            image: require("../assets/images/dishes/pizza-3.jpg"),
          },
          {
            id: 2,
            name: "Tandoor Panner Pizza",
            description: "Pizza Hut",
            price: 450,
            image: require("../assets/images/dishes/pizza-2.jpg"),
          },
          {
            id: 3,
            name: "Classic Sweet Corn Pizza",
            description: "Pizza Hut",
            price: 250,
            image: require("../assets/images/dishes/pizza-1.jpg"),
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Burger King",
    description: "60% OFF Upto ₹120",
    restaurants: [
      {
        id: 1,
        title: "Burger King",
        name: "BK Veggie Burger",
        image: require("../assets/images/dishes/burger-1.jpg"),
        description:
          "Explore curated lists of top restaurants, cafes, pubs, and bars in Delhi NCR, based on trends",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "₹189 For One",
        dishes: [
          {
            id: 1,
            name: "BK Veggie Burger",
            description: "Burger King",
            price: 189,
            image: require("../assets/images/dishes/burger-1.jpg"),
          },
          {
            id: 2,
            name: "Paneer Royale Burger",
            description: "Burger King",
            price: 169,
            image: require("../assets/images/dishes/burger-2.jpg"),
          },
          {
            id: 3,
            name: "Crispy Veg Burger",
            description: "Burger King",
            price: 70,
            image: require("../assets/images/dishes/burger-3.jpg"),
          },
        ],
      },
      {
        id: 2,
        title: "Burger King",
        name: "Paneer Royale Burger",
        image: require("../assets/images/dishes/burger-2.jpg"),
        description:
          "Explore curated lists of top restaurants, cafes, pubs, and bars in Delhi NCR, based on trends",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "₹169 For One",
        dishes: [
          {
            id: 1,
            name: "Paneer Royale Burger",
            description: "Burger King",
            price: 169,
            image: require("../assets/images/dishes/burger-2.jpg"),
          },
          {
            id: 2,
            name: "BK Veggie Burger",
            description: "Burger King",
            price: 189,
            image: require("../assets/images/dishes/burger-1.jpg"),
          },
          {
            id: 3,
            name: "Crispy Veg Burger",
            description: "Burger King",
            price: 70,
            image: require("../assets/images/dishes/burger-3.jpg"),
          },
        ],
      },
      {
        id: 3,
        title: "Burger King",
        name: "Crispy Veg Burger",
        image: require("../assets/images/dishes/burger-3.jpg"),
        description:
          "Explore curated lists of top restaurants, cafes, pubs, and bars in Delhi NCR, based on trends",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "₹70 For One",
        dishes: [
          {
            id: 1,
            name: "Crispy Veg Burger",
            description: "Burger King",
            price: 70,
            image: require("../assets/images/dishes/burger-3.jpg"),
          },
          {
            id: 2,
            name: "BK Veggie Burger",
            description: "Burger King",
            price: 189,
            image: require("../assets/images/dishes/burger-1.jpg"),
          },
          {
            id: 3,
            name: "Paneer Royale Burger",
            description: "Burger King",
            price: 169,
            image: require("../assets/images/dishes/burger-2.jpg"),
          },
        ],
      },
    ],
  },
];
